services:
    user:
        class: vinabb\demostyles\controller\user
        arguments:
            - %datetime.class%
    vinabb.demostyles.controller:
        class: vinabb\demostyles\controller\main
        arguments:
            - @dbal.conn
            - @config
            - @controller.helper
            - @template
            - @user
            - @auth
            - @request
            - @ext.manager
            - @path_helper
            - %core.root_path%
            - %core.adm_relative_path%
            - %core.php_ext%
    vinabb.demostyles.listener:
        class: vinabb\demostyles\event\listener
        arguments:
            - @dbal.conn
            - @config
            - @controller.helper
            - @template
            - @user
            - @request
            - %core.root_path%
            - %core.adm_relative_path%
            - %core.php_ext%
        tags:
            - { name: event.listener }
