imports:
    - { resource: tables.yml }

services:
    user:
        class: vinabb\stylesdemo\controller\user
        arguments:
            - '%datetime.class%'
    vinabb.stylesdemo.controller:
        class: vinabb\stylesdemo\controller\main
        arguments:
            - '@dbal.conn'
            - '@cache.driver'
            - '@config'
            - '@controller.helper'
            - '@template'
            - '@user'
            - '@auth'
            - '@request'
            - '@ext.manager'
            - '@path_helper'
            - '@file_downloader'
            - '%vinabb.stylesdemo.tables.acp_styles%'
            - '%core.root_path%'
            - '%core.adm_relative_path%'
            - '%core.php_ext%'
    vinabb.stylesdemo.listener:
        class: vinabb\stylesdemo\event\listener
        arguments:
            - '@cache.driver'
            - '@config'
            - '@controller.helper'
            - '@template'
            - '@user'
            - '@ext.manager'
            - '@path_helper'
            - '%core.root_path%'
            - '%core.adm_relative_path%'
            - '%core.php_ext%'
        tags:
            - { name: event.listener }
