imports:
    - { resource: tables.yml }

services:
    vinabb.stylesdemo.decorates.user:
        class: vinabb\stylesdemo\decorates\user
        decorates: user
        arguments:
            - '@language'
            - '%datetime.class%'
    vinabb.stylesdemo.helper:
        class: vinabb\stylesdemo\controllers\helper
        arguments:
            - '@auth'
            - '@dbal.conn'
            - '@log'
            - '@user'
    vinabb.stylesdemo.entities.style:
        class: vinabb\stylesdemo\entities\style
        arguments:
            - '@dbal.conn'
            - '%core.root_path%'
            - '%tables.styles%'
    vinabb.stylesdemo.entities.acp_style:
        class: vinabb\stylesdemo\entities\acp_style
        arguments:
            - '@dbal.conn'
            - '@ext.manager'
            - '%vinabb.stylesdemo.tables.acp_styles%'
    vinabb.web.operators.style:
        class: vinabb\stylesdemo\operators\style
        arguments:
            - '@service_container'
            - '@dbal.conn'
            - '%tables.styles%'
    vinabb.web.operators.acp_style:
        class: vinabb\stylesdemo\operators\acp_style
        arguments:
            - '@service_container'
            - '@dbal.conn'
            - '%vinabb.stylesdemo.tables.acp_styles%'
    vinabb.stylesdemo.controller:
        class: vinabb\stylesdemo\controllers\main
        arguments:
            - '@dbal.conn'
            - '@cache.driver'
            - '@config'
            - '@controller.helper'
            - '@template'
            - '@user'
            - '@language'
            - '@auth'
            - '@request'
            - '@ext.manager'
            - '@path_helper'
            - '@file_downloader'
            - '%vinabb.stylesdemo.tables.acp_styles%'
            - '%core.root_path%'
            - '%core.php_ext%'
    vinabb.stylesdemo.listener:
        class: vinabb\stylesdemo\events\listener
        arguments:
            - '@cache.driver'
            - '@config'
            - '@controller.helper'
            - '@template'
            - '@user'
            - '@language'
            - '@ext.manager'
            - '@path_helper'
            - '%core.root_path%'
            - '%core.adm_relative_path%'
            - '%core.php_ext%'
        tags:
            - { name: event.listener }
